///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsStoryObject {
/*
{
  "story_id": 2,
  "author_id": 1,
  "video_link": "",
  "created_at": "2021-09-08 16:33:14",
  "title": "",
  "descption": "",
  "view_count": 0,
  "total_watch_time": 0,
  "avg_user_watch_time": 0,
  "likes_count": 0,
  "share_count": 0,
  "comments_count": 0
}
*/

  int? storyId;
  int? authorId;
  String? videoLink;
  String? thumLink;
  String? createdAt;
  String? title;
  String? descption;
  int? viewCount;
  int? totalWatchTime;
  int? avgUserWatchTime;
  int? likesCount;
  int? shareCount;
  int? commentsCount;
  Map<String, dynamic> __origJson = {};

  NewsStoryObject({
    this.storyId,
    this.authorId,
    this.videoLink,
    this.thumLink,
    this.createdAt,
    this.title,
    this.descption,
    this.viewCount,
    this.totalWatchTime,
    this.avgUserWatchTime,
    this.likesCount,
    this.shareCount,
    this.commentsCount,
  });
  NewsStoryObject.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    storyId = int.tryParse(json["story_id"]?.toString() ?? '');
    authorId = int.tryParse(json["author_id"]?.toString() ?? '');
    videoLink = json["video_link"]?.toString();
    thumLink = json["thum_link"]?.toString();
    createdAt = json["created_at"]?.toString();
    title = json["title"]?.toString();
    descption = json["descption"]?.toString();
    viewCount = int.tryParse(json["view_count"]?.toString() ?? '');
    totalWatchTime = int.tryParse(json["total_watch_time"]?.toString() ?? '');
    avgUserWatchTime =
        int.tryParse(json["avg_user_watch_time"]?.toString() ?? '');
    likesCount = int.tryParse(json["likes_count"]?.toString() ?? '');
    shareCount = int.tryParse(json["share_count"]?.toString() ?? '');
    commentsCount = int.tryParse(json["comments_count"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["story_id"] = storyId;
    data["author_id"] = authorId;
    data["video_link"] = videoLink;
    data["thum_link"] = thumLink;
    data["created_at"] = createdAt;
    data["title"] = title;
    data["descption"] = descption;
    data["view_count"] = viewCount;
    data["total_watch_time"] = totalWatchTime;
    data["avg_user_watch_time"] = avgUserWatchTime;
    data["likes_count"] = likesCount;
    data["share_count"] = shareCount;
    data["comments_count"] = commentsCount;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
