///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserObject {
/*
{
  "user_id": 1,
  "name": "Ankit Jain ",
  "username": null,
  "email": "ajain.aj1996@gmail.com",
  "sign_in_token": "eyJraWQiOiJBaE1JeXQzbkN3UDl6SkptVDRCWDhIMFJESlE1NllMcXRyaWZuY0trOFJRPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiWktTeUhuYXBYWV8yOElBVEhvUno1USIsInN1YiI6IjkxOTJmZGJmLTFiODktNGQ4Yi04NjY1LTNlYTFkZTRmOTgxYiIsImNvZ25pdG86Z3JvdXBzIjpbImV1LXdlc3QtMl9KcmJZOEZhcmtfR29vZ2xlIl0sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmV1LXdlc3QtMi5hbWF6b25hd3MuY29tXC9ldS13ZXN0LTJfSnJiWThGYXJrIiwiY29nbml0bzp1c2VybmFtZSI6Imdvb2dsZV8xMTU4MDkzNDkyNjkzNDMzODY1ODQiLCJub25jZSI6IkhPVURDOHZrNVB4Ny04SUdUSWpGVFJvVHNNNzlKSldLa29FSGQtSERTa0lGQ0QtcWwxUElBWVZQTVpfOUhXN1ZTMlBzR0lfSFZRMjBubzNlYXBMcG4xbFNNQ0ZldEl0U1lDYWNWWk9nUDA5M1lGOEJqeWhwMGZia094Z29sNTFuR0tPY2IzYmN3TXozOE9VRVNRTC1zSDhJMndGTkNXa2E3RlUxbEQ3am9ySSIsIm9yaWdpbl9qdGkiOiI4OTlhNDhiYS01NzlmLTQwYTAtYTljMi0xZTc5NTBiYjViNWIiLCJhdWQiOiJyNm5mb2JvanNydnFtYmU4YWZnN3B1aGgxIiwiaWRlbnRpdGllcyI6W3sidXNlcklkIjoiMTE1ODA5MzQ5MjY5MzQzMzg2NTg0IiwicHJvdmlkZXJOYW1lIjoiR29vZ2xlIiwicHJvdmlkZXJUeXBlIjoiR29vZ2xlIiwiaXNzdWVyIjpudWxsLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTYzMDY1OTM4MjY2MSJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2MzA2NTkzODMsImV4cCI6MTYzMDY2Mjk4MywiaWF0IjoxNjMwNjU5Mzg0LCJqdGkiOiIwYmQ2OThlMi0wMGJjLTRhZTEtYmM3MC1hOTJjNjU5YjgxODQiLCJlbWFpbCI6ImFqYWluLmFqMTk5NkBnbWFpbC5jb20ifQ.7DbDwuWopJqQRjDydFknEA4e9-6w7u0HC63Y8MUrJ8jqKqwtcQ4k6np7uwLcTXjyM5qantNnj-vZJoCa-YTYXRwsgLXbVYZuNmfJ_DACGnXL1-otjQ1-GWspkmqdKCPmmX423uvWQydgttPzIr-FTHCqD5237NOaEeh3E9ngsx0IruvApE4GlKZ1Z3hk6nx8GfQ8frFL8GAZ-uMNMyrMGxU0-1nBal_Av3sIVl-cDp9DoiMDd7O8VHrgFdfg2zKPoHhR9B_Bn3tV8FMkK-P8c1W5aJPrwEYuxLN-vKQzy3Iak1g3z0WliVsmQowges2XujdFE-EqyJIxE6BZu2qjVQ",
  "gender": null,
  "age": null,
  "created_at": "2021-09-03 08:56:40",
  "signup_src": null,
  "last_used_time": null,
  "is_online": 0,
  "language": null,
  "bio": null,
  "iscreator": false,
  "link": null,
  "follower_count": 0,
  "following_count": 0,
  "answer_count": 0,
  "question_count": 0,
  "question_following_count": 0,
  "total_upvotes_count": 0,
  "total_downvotes_count": 0,
  "total_answers_seen_count": 0,
  "total_question_seen_count": 0,
  "total_news_seen_count": 0,
  "total_share_count": 0,
  "news_stories_count": 0,
  "total_views_count": 0,
  "total_news_likes_count": 0,
  "total_watch_time_earned": 0,
  "avg_watch_time_earned": 0,
  "total_watch_time": 0,
  "avg_watch_time": 0,
  "total_watch_time_earned_news": 0,
  "avg_watch_time_earned_news": 0,
  "total_watch_time_news": 0,
  "avg_watch_time_news": 0
}
*/

  int? userId;
  String? name;
  String? username;
  String? email;
  String? signInToken;
  String? gender;
  String? age;
  String? createdAt;
  String? signupSrc;
  String? lastUsedTime;
  int? isOnline;
  String? language;
  String? bio;
  bool? iscreator;
  String? link;
  int? followerCount;
  int? followingCount;
  int? answerCount;
  int? questionCount;
  int? questionFollowingCount;
  int? totalUpvotesCount;
  int? totalDownvotesCount;
  int? totalAnswersSeenCount;
  int? totalQuestionSeenCount;
  int? totalNewsSeenCount;
  int? totalShareCount;
  int? newsStoriesCount;
  int? totalViewsCount;
  int? totalNewsLikesCount;
  int? totalWatchTimeEarned;
  int? avgWatchTimeEarned;
  int? totalWatchTime;
  int? avgWatchTime;
  int? totalWatchTimeEarnedNews;
  int? avgWatchTimeEarnedNews;
  int? totalWatchTimeNews;
  int? avgWatchTimeNews;
  Map<String, dynamic> __origJson = {};

  UserObject({
    this.userId,
    this.name,
    this.username,
    this.email,
    this.signInToken,
    this.gender,
    this.age,
    this.createdAt,
    this.signupSrc,
    this.lastUsedTime,
    this.isOnline,
    this.language,
    this.bio,
    this.iscreator,
    this.link,
    this.followerCount,
    this.followingCount,
    this.answerCount,
    this.questionCount,
    this.questionFollowingCount,
    this.totalUpvotesCount,
    this.totalDownvotesCount,
    this.totalAnswersSeenCount,
    this.totalQuestionSeenCount,
    this.totalNewsSeenCount,
    this.totalShareCount,
    this.newsStoriesCount,
    this.totalViewsCount,
    this.totalNewsLikesCount,
    this.totalWatchTimeEarned,
    this.avgWatchTimeEarned,
    this.totalWatchTime,
    this.avgWatchTime,
    this.totalWatchTimeEarnedNews,
    this.avgWatchTimeEarnedNews,
    this.totalWatchTimeNews,
    this.avgWatchTimeNews,
  });
  UserObject.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    userId = int.tryParse(json["user_id"]?.toString() ?? '');
    name = json["name"]?.toString();
    username = json["username"]?.toString();
    email = json["email"]?.toString();
    signInToken = json["sign_in_token"]?.toString();
    gender = json["gender"]?.toString();
    age = json["age"]?.toString();
    createdAt = json["created_at"]?.toString();
    signupSrc = json["signup_src"]?.toString();
    lastUsedTime = json["last_used_time"]?.toString();
    isOnline = int.tryParse(json["is_online"]?.toString() ?? '');
    language = json["language"]?.toString();
    bio = json["bio"]?.toString();
    iscreator = json["iscreator"];
    link = json["link"]?.toString();
    followerCount = int.tryParse(json["follower_count"]?.toString() ?? '');
    followingCount = int.tryParse(json["following_count"]?.toString() ?? '');
    answerCount = int.tryParse(json["answer_count"]?.toString() ?? '');
    questionCount = int.tryParse(json["question_count"]?.toString() ?? '');
    questionFollowingCount = int.tryParse(json["question_following_count"]?.toString() ?? '');
    totalUpvotesCount = int.tryParse(json["total_upvotes_count"]?.toString() ?? '');
    totalDownvotesCount = int.tryParse(json["total_downvotes_count"]?.toString() ?? '');
    totalAnswersSeenCount = int.tryParse(json["total_answers_seen_count"]?.toString() ?? '');
    totalQuestionSeenCount = int.tryParse(json["total_question_seen_count"]?.toString() ?? '');
    totalNewsSeenCount = int.tryParse(json["total_news_seen_count"]?.toString() ?? '');
    totalShareCount = int.tryParse(json["total_share_count"]?.toString() ?? '');
    newsStoriesCount = int.tryParse(json["news_stories_count"]?.toString() ?? '');
    totalViewsCount = int.tryParse(json["total_views_count"]?.toString() ?? '');
    totalNewsLikesCount = int.tryParse(json["total_news_likes_count"]?.toString() ?? '');
    totalWatchTimeEarned = int.tryParse(json["total_watch_time_earned"]?.toString() ?? '');
    avgWatchTimeEarned = int.tryParse(json["avg_watch_time_earned"]?.toString() ?? '');
    totalWatchTime = int.tryParse(json["total_watch_time"]?.toString() ?? '');
    avgWatchTime = int.tryParse(json["avg_watch_time"]?.toString() ?? '');
    totalWatchTimeEarnedNews = int.tryParse(json["total_watch_time_earned_news"]?.toString() ?? '');
    avgWatchTimeEarnedNews = int.tryParse(json["avg_watch_time_earned_news"]?.toString() ?? '');
    totalWatchTimeNews = int.tryParse(json["total_watch_time_news"]?.toString() ?? '');
    avgWatchTimeNews = int.tryParse(json["avg_watch_time_news"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["user_id"] = userId;
    data["name"] = name;
    data["username"] = username;
    data["email"] = email;
    data["sign_in_token"] = signInToken;
    data["gender"] = gender;
    data["age"] = age;
    data["created_at"] = createdAt;
    data["signup_src"] = signupSrc;
    data["last_used_time"] = lastUsedTime;
    data["is_online"] = isOnline;
    data["language"] = language;
    data["bio"] = bio;
    data["iscreator"] = iscreator;
    data["link"] = link;
    data["follower_count"] = followerCount;
    data["following_count"] = followingCount;
    data["answer_count"] = answerCount;
    data["question_count"] = questionCount;
    data["question_following_count"] = questionFollowingCount;
    data["total_upvotes_count"] = totalUpvotesCount;
    data["total_downvotes_count"] = totalDownvotesCount;
    data["total_answers_seen_count"] = totalAnswersSeenCount;
    data["total_question_seen_count"] = totalQuestionSeenCount;
    data["total_news_seen_count"] = totalNewsSeenCount;
    data["total_share_count"] = totalShareCount;
    data["news_stories_count"] = newsStoriesCount;
    data["total_views_count"] = totalViewsCount;
    data["total_news_likes_count"] = totalNewsLikesCount;
    data["total_watch_time_earned"] = totalWatchTimeEarned;
    data["avg_watch_time_earned"] = avgWatchTimeEarned;
    data["total_watch_time"] = totalWatchTime;
    data["avg_watch_time"] = avgWatchTime;
    data["total_watch_time_earned_news"] = totalWatchTimeEarnedNews;
    data["avg_watch_time_earned_news"] = avgWatchTimeEarnedNews;
    data["total_watch_time_news"] = totalWatchTimeNews;
    data["avg_watch_time_news"] = avgWatchTimeNews;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
